# Generated by Django 6.1.1 on 2026-10-06 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('required_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('available', 'Available'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('qr_token', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive')], default='active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QR_WorkTracker.job')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QR_WorkTracker.machine')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.workerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Pause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('break', 'Break'), ('maintenance', 'Maintenance'), ('other', 'Other')], default='break', max_length=20)),
                ('explanation', models.TextField(blank=True)),
                ('work_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QR_WorkTracker.worksession')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QR_WorkTracker.job')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='QR_WorkTracker.machine')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('job', 'machine'), name='unique_job_machine')],
            },
        ),
    ]
