# Generated by Django 6.1.1 on 2026-10-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(unique=True)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('worker', 'Worker'), ('admin', 'Admin')], default='worker', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
